api_platform:
  mapping:
    paths: [ '%kernel.project_dir%/src/Entity' ]
  patch_formats:
    json: [ 'application/merge-patch+json' ]

  formats:
    jsonld: [ 'application/ld+json' ]
    json: [ 'application/json' ]
  show_webby: false
  swagger:
    versions: [ 3 ]
