version: '3'

services:

  app_pgsql:
    image: postgres:13-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: phonebook-user
      POSTGRES_PASSWORD: phonebook-app-password
      POSTGRES_DB: phonebook-app
    ports:
      - '5432:5432'

  app_adminer:
    image: adminer
    restart: on-failure
    ports:
      - '8080:8080'
